### ISSUE TITLE
Future development?

### ISSUE THREAD

**Issue by kescobo** [rasmushenningsson/SynapseClient.jl#1]
Hello! I'm about to start working on a project where I'll be using synapse, and I was wondering what your interest is in future development. It doesn't look like you ever registered this package in the General registry after the 1.0 switch, and stopped working on this package around that time.

I'd be happy to just maintain a separate fork if you're no longer interested in working on it, but could also make PRs against this repo and work with you if you'd like to maintain a hand in it.

I think my preference would be to use what you have here as a base, but work on moving away from the dependency on python by slowly peeling off functions to rewrite in pure julia.

**Comment by rasmushenningsson** [comment]
Hi!

I don't have any time to put into SynapseClient.jl in the foreseeable future, but I would be very happy to see it live on. A fork is probably the best way forward.

Feel free to change anything, I took a minimal effort approach to have it up and running quickly.
A pure Julia implementation (based on the REST API I guess?) would definitely be more convenient for users.

**Comment by kescobo** [comment]
:+1: sounds good - I'll maintain [a fork](https://github.com/kescobo/SynapseClient.jl) for now (this is going to be on the side over the course of the next year or more), and I'll check back in if it ever makes sense to register the package (in which case we can upstream any changes, or move it to an org or something).
